### ISSUE TITLE
memory address should be in the format XXX0 error

### ISSUE THREAD

**Issue by himalaya0035** [8085simulator/8085simulator#4]
Hi Jubin
While running your simulator I am facing this error 
![image](https://user-images.githubusercontent.com/61822515/135989436-a92b2121-dcad-4ca8-b033-cf5350cc2233.png)

**Comment by himalaya0035** [comment]
What to do ??

**Comment by himalaya0035** [comment]
solved

**Comment by kubra-khan-sa** [comment]
How did you solve the error

**Comment by ghost** [comment]
> 

How did you solve this?

**Comment by SouZe-San** [comment]
go  to this file's properties --> change its default opener to "JAVA(TM) platform SE binary"

<img width="284" alt="Screenshot 2023-09-06 212113" src="https://github.com/8085simulator/8085simulator/assets/103335953/fcfa434d-e13f-4f66-9e8f-c125573d9006">

**Comment by nextpointer** [comment]
> go to this file's properties --> change its default opener to "JAVA(TM) platform SE binary"
> <img alt="Screenshot 2023-09-06 212113" width="284" src="https://user-images.githubusercontent.com/103335953/266068076-fcfa434d-e13f-4f66-9e8f-c125573d9006.png">


O really ?????????????????????????? 😮 
btw i have already solved it 😎
